def count_distinct_terms(a_min, a_max, b_min, b_max):
    distinct_terms = set()

    for a in range(a_min, a_max + 1):
        for b in range(b_min, b_max + 1):
            distinct_terms.add(a ** b)

    return len(distinct_terms)


a_min, a_max = 2, 100
b_min, b_max = 2, 100

result = count_distinct_terms(a_min, a_max, b_min, b_max)
print(
    f"The number of distinct terms in the sequence generated by a^b for {a_min} ≤ a ≤ {a_max} and {b_min} ≤ b ≤ {b_max} is: {result}")